export const supportedLanguages = [
  // { "code": "af", "name": "Afrikaans", "nativeName": "Afrikaans" },
  // { "code": "sq", "name": "Albanian", "nativeName": "Shqip" },
  // { "code": "ar", "name": "Arabic", "nativeName": "اللغة العربية" },
  // { "code": "hy", "name": "Armenian", "nativeName": "Հայերեն" },
  // { "code": "az", "name": "Azerbaijani", "nativeName": "azərbaycan dili" },
  // { "code": "eu", "name": "Basque", "nativeName": "euskara" },
  // { "code": "be", "name": "Belarusian", "nativeName": "беларуская мова" },
  // { "code": "bn", "name": "Bengali", "nativeName": "বাংলা" },
  // { "code": "bs", "name": "Bosnian", "nativeName": "bosanski jezik" },
  // { "code": "bg", "name": "Bulgarian", "nativeName": "български език" },
  // { "code": "my", "name": "Burmese", "nativeName": "ဗမာစာ" },
  // { "code": "ca", "name": "Catalan", "nativeName": "Català" },
  // { "code": "zh", "name": "Chinese", "nativeName": "中文" },
  // { "code": "cs", "name": "Czech", "nativeName": "čeština" },
  // { "code": "da", "name": "Danish", "nativeName": "dansk" },
  // { "code": "nl", "name": "Dutch", "nativeName": "Nederlands" },
  { "code": "en", "name": "English", "nativeName": "English" },
  // { "code": "et", "name": "Estonian", "nativeName": "eesti" },
  // { "code": "fi", "name": "Finnish", "nativeName": "suomi" },
  // { "code": "fr", "name": "French", "nativeName": "Français" },
  // { "code": "gl", "name": "Galician", "nativeName": "galego" },
  // { "code": "ka", "name": "Georgian", "nativeName": "ქართული" },
  // { "code": "de", "name": "German", "nativeName": "Deutsch" },
  // { "code": "el", "name": "Greek", "nativeName": "Ελληνικά" },
  // { "code": "gu", "name": "Gujarati", "nativeName": "ગુજરાતી" },
  // { "code": "ha", "name": "Hausa", "nativeName": "هَوُسَ" },
  // { "code": "hi", "name": "Hindi", "nativeName": "हिन्दी" },
  // { "code": "hu", "name": "Hungarian", "nativeName": "magyar" },
  // { "code": "is", "name": "Icelandic", "nativeName": "Íslenska" },
  // { "code": "id", "name": "Indonesian", "nativeName": "Bahasa Indonesia" },
  // { "code": "ga", "name": "Irish", "nativeName": "Gaeilge" },
  // { "code": "it", "name": "Italian", "nativeName": "Italiano" },
  // { "code": "ja", "name": "Japanese", "nativeName": "日本語" },
  // { "code": "kn", "name": "Kannada", "nativeName": "ಕನ್ನಡ" },
  // { "code": "kk", "name": "Kazakh", "nativeName": "қазақ тілі" },
  // { "code": "km", "name": "Khmer", "nativeName": "ខេមរភាសា" },
  // { "code": "rw", "name": "Kinyarwanda", "nativeName": "Ikinyarwanda" },
  // { "code": "ko", "name": "Korean", "nativeName": "한국어" },
  // { "code": "ku", "name": "Kurdish", "nativeName": "Kurdî" },
  // { "code": "ky", "name": "Kyrgyz", "nativeName": "Кыргызча" },
  // { "code": "lo", "name": "Lao", "nativeName": "ພາສາ" },
  // { "code": "lv", "name": "Latvian", "nativeName": "latviešu valoda" },
  // { "code": "lt", "name": "Lithuanian", "nativeName": "lietuvių kalba" },
  // { "code": "lb", "name": "Luxembourgish", "nativeName": "Lëtzebuergesch" },
  // { "code": "mk", "name": "Macedonian", "nativeName": "македонски јазик" },
  // { "code": "mg", "name": "Malagasy", "nativeName": "fiteny malagasy" },
  // { "code": "ms", "name": "Malay", "nativeName": "Bahasa Malaysia" },
  // { "code": "ml", "name": "Malayalam", "nativeName": "മലയാളം" },
  // { "code": "mt", "name": "Maltese", "nativeName": "Malti" },
  // { "code": "mr", "name": "Marathi", "nativeName": "मराठी" },
  // { "code": "mn", "name": "Mongolian", "nativeName": "Монгол хэл" },
  // { "code": "mi", "name": "Māori", "nativeName": "te reo Māori" },
  // { "code": "ne", "name": "Nepali", "nativeName": "नेपाली" },
  // { "code": "no", "name": "Norwegian", "nativeName": "Norsk" },
  // { "code": "or", "name": "Oriya", "nativeName": "ଓଡ଼ିଆ" },
  // { "code": "pa", "name": "Panjabi", "nativeName": "ਪੰਜਾਬੀ" },
  // { "code": "ps", "name": "Pashto", "nativeName": "پښتو" },
  // { "code": "fa", "name": "Persian", "nativeName": "فارسی" },
  // { "code": "pl", "name": "Polish", "nativeName": "język polski" },
  // { "code": "pt", "name": "Portuguese", "nativeName": "Português" },
  // { "code": "ro", "name": "Romanian", "nativeName": "Română" },
  { "code": "ru", "name": "Russian", "nativeName": "Русский" },
  // { "code": "sm", "name": "Samoan", "nativeName": "gagana fa'a Samoa" },
  // { "code": "gd", "name": "Scottish Gaelic", "nativeName": "Gàidhlig" },
  // { "code": "sr", "name": "Serbian", "nativeName": "српски језик" },
  // { "code": "sn", "name": "Shona", "nativeName": "chiShona" },
  // { "code": "sd", "name": "Sindhi", "nativeName": "सिन्धी" },
  // { "code": "si", "name": "Sinhala", "nativeName": "සිංහල" },
  // { "code": "sk", "name": "Slovak", "nativeName": "slovenčina" },
  // { "code": "sl", "name": "Slovene", "nativeName": "slovenski jezik" },
  // { "code": "so", "name": "Somali", "nativeName": "Soomaaliga" },
  // { "code": "es", "name": "Spanish", "nativeName": "Español" },
  // { "code": "su", "name": "Sundanese", "nativeName": "Basa Sunda" },
  // { "code": "sw", "name": "Swahili", "nativeName": "Kiswahili" },
  // { "code": "sv", "name": "Swedish", "nativeName": "Svenska" },
  // { "code": "tl", "name": "Tagalog", "nativeName": "Wikang Tagalog" },
  // { "code": "tg", "name": "Tajik", "nativeName": "тоҷикӣ" },
  // { "code": "ta", "name": "Tamil", "nativeName": "தமிழ்" },
  // { "code": "tt", "name": "Tatar", "nativeName": "татар теле" },
  // { "code": "te", "name": "Telugu", "nativeName": "తెలుగు" },
  // { "code": "th", "name": "Thai", "nativeName": "ไทย" },
  // { "code": "tr", "name": "Turkish", "nativeName": "Türkçe" },
  // { "code": "tk", "name": "Turkmen", "nativeName": "Türkmen" },
  // { "code": "uk", "name": "Ukrainian", "nativeName": "Українська" },
  // { "code": "ur", "name": "Urdu", "nativeName": "اردو" },
  // { "code": "ug", "name": "Uyghur", "nativeName": "ئۇيغۇرچە‎" },
  // { "code": "uz", "name": "Uzbek", "nativeName": "Ўзбек" },
  // { "code": "vi", "name": "Vietnamese", "nativeName": "Tiếng Việt" },
  // { "code": "cy", "name": "Welsh", "nativeName": "Cymraeg" },
  // { "code": "fy", "name": "Western Frisian", "nativeName": "Frysk" },
  // { "code": "xh", "name": "Xhosa", "nativeName": "isiXhosa" },
  // { "code": "yi", "name": "Yiddish", "nativeName": "ייִדיש" },
  // { "code": "zu", "name": "Zulu", "nativeName": "isiZulu" },
  // { "code": "zu", "name": "Zulu", "nativeName": "isiZulu" }
]

export const getLanguageName = (languageCode: string | null): string => {
  if (languageCode === null) {
    return 'unknown'
  }

  languageCode = languageCode.substring(0, 2)

  let language = supportedLanguages.find((language) => language.code === languageCode)

  if (language) {
    return language.name
  }

  return 'unknown'
}
